name: Rotate
favicon: null
layout_spectrum: 0.47052
typography_spectrum: 1
title: 肉桂數位行銷
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fefefe'
    - '#e1e4cf'
    - '#8fa461'
    - '#6d6f64'
    - '#2f3d2e'
  brandStrength: 0.8125
  lightness: 0
  saturation: 0.5625
  rhythmicContrast: 0.5261154340114444
purpose: []
